packages:
  - 'backend'
  - 'frontend'

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - 'argon2'
  - 'esbuild'
  - 'msgpackr-extract'
  - 'msw'
  - 'nx'
  - 'prisma'
  - 'unrs-resolver'

overrides:
  js-yaml: '>=5.2.2'
  uuid: ^11.1.1
  multer: ^2.2.0
  brace-expansion: '>=2.1.4'
  brace-expansion@1: '>=1.1.18'
  brace-expansion@2: '>=2.1.4'
  brace-expansion@3: '>=3.0.6'
  brace-expansion@5: '>=5.0.9'
  ip-address: '>=10.3.1'
  picomatch: '>=4.0.4'
  sigstore: '>=4.1.1'
  tmp: '>=0.2.6'
  esbuild: '>=0.28.2'
  qs: '>=6.15.2'
  '@puppeteer/browsers': '>=3.2.1'
