packages:
  - 'backend'
  - 'frontend'

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - 'argon2'
  - 'esbuild'
  - 'msgpackr-extract'
  - 'msw'
  - 'nx'
  - 'prisma'
  - 'unrs-resolver'
