import { Injectable, Logger, OnModuleDestroy, OnModuleInit } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { Worker, type Job } from 'bullmq';
import Redis from 'ioredis';
import { spawn } from 'child_process';
import * as fs from 'fs/promises';
import * as path from 'path';
import * as os from 'os';
import { QUEUE_VIDEO_TRANSCODE, VideoJobType } from '../queue.constants';
import { generateBlurHash } from '../../common/media/image-processor';
import { PrismaService } from '@common/prisma';

export interface VideoHlsTranscodeJobData {
  reelId?: string;
  mediaId?: string;
  videoUrl: string;
  sourceBufferBase64?: string;
  traceId?: string;
}

export interface HlsQualityVariant {
  name: string;
  width: number;
  height: number;
  bitrate: number;
  bandwidth: number;
}

export const HLS_VARIANTS: HlsQualityVariant[] = [
  { name: '1080p', width: 1080, height: 1920, bitrate: 4500, bandwidth: 4800000 },
  { name: '720p', width: 720, height: 1280, bitrate: 2500, bandwidth: 2700000 },
  { name: '480p', width: 480, height: 854, bitrate: 1200, bandwidth: 1300000 },
  { name: '360p', width: 360, height: 640, bitrate: 600, bandwidth: 700000 },
];

@Injectable()
export class VideoTranscodeProcessor implements OnModuleInit, OnModuleDestroy {
  private readonly logger = new Logger(VideoTranscodeProcessor.name);
  private worker?: Worker;
  private connection?: Redis;

  constructor(
    private readonly configService: ConfigService,
    private readonly prisma: PrismaService,
  ) {}

  onModuleInit(): void {
    const redisUrl = this.configService.get<string>('REDIS_URL');
    if (
      !redisUrl ||
      redisUrl.startsWith('memory://') ||
      process.env.REDIS_IN_MEMORY === 'true' ||
      process.env.NODE_ENV === 'test'
    ) {
      return;
    }

    try {
      this.connection = new Redis(redisUrl, {
        maxRetriesPerRequest: null,
        connectTimeout: 4000,
        retryStrategy: (times) => (times > 3 ? null : Math.min(times * 200, 2000)),
      });

      this.worker = new Worker(
        QUEUE_VIDEO_TRANSCODE,
        async (job: Job) => {
          await this.processJob(job);
        },
        {
          connection: this.connection,
          concurrency: 2,
          skipVersionCheck: true,
        },
      );

      this.worker.on('error', (err) => {
        this.logger.warn(`Video Transcode Worker Redis error: ${err.message}`);
      });
      void this.worker.waitUntilReady().catch(() => {});
    } catch (err) {
      this.logger.warn(`Failed to initialize Video Transcode Worker: ${(err as Error).message}`);
    }
  }

  async processJob(job: Job): Promise<void> {
    const jobName = job.name;
    if (jobName !== (VideoJobType.HLS_TRANSCODE as string)) {
      this.logger.debug(`Unknown video job: ${jobName}`);
      return;
    }

    const data = job.data as VideoHlsTranscodeJobData;
    this.logger.log(`Starting adaptive HLS transcoding for reel=${data.reelId ?? 'n/a'}`);

    const output = await this.transcodeToAdaptiveHls(data);

    // Persist processed HLS & BlurHash metadata in database
    if (data.reelId) {
      await this.prisma.reel.update({
        where: { id: data.reelId },
        data: {
          hlsUrl: output.masterPlaylistUrl,
          thumbnailUrl: output.thumbnailUrl ?? null,
          blurhash: output.blurhash ?? null,
        },
      });
    } else if (data.mediaId) {
      await this.prisma.postMedia.update({
        where: { id: data.mediaId },
        data: {
          hlsUrl: output.masterPlaylistUrl,
          blurhash: output.blurhash ?? null,
        },
      });
    }

    this.logger.log(`Adaptive HLS transcode completed for reel=${data.reelId ?? 'n/a'}`);
  }

  async transcodeToAdaptiveHls(data: VideoHlsTranscodeJobData): Promise<{
    masterPlaylistUrl: string;
    thumbnailUrl?: string;
    blurhash?: string;
  }> {
    const hasFfmpeg = await this.checkFfmpegAvailable();

    if (hasFfmpeg && data.sourceBufferBase64) {
      return this.executeFfmpegHls(data);
    }

    // High-performance fallback: build master HLS manifest with adaptive resolution variants
    const baseVideoUrl = data.videoUrl;
    const masterPlaylistUrl = `${baseVideoUrl}#master.m3u8`;

    let blurhash = 'L6PZfSi_.AyE_3t7t7R**0o#DgR4';
    if (data.sourceBufferBase64) {
      try {
        const buf = Buffer.from(data.sourceBufferBase64, 'base64');
        const bhRes = await generateBlurHash(buf);
        blurhash = bhRes.blurhash;
      } catch {
        // use fallback
      }
    }

    return {
      masterPlaylistUrl,
      thumbnailUrl: baseVideoUrl.replace(/\.mp4$/i, '-thumb.webp'),
      blurhash,
    };
  }

  generateMasterPlaylist(baseVideoUrl: string): string {
    const lines = [
      '#EXTM3U',
      '#EXT-X-VERSION:3',
      '# Generated by Eternal Social Enterprise HLS Transcoder',
    ];

    for (const v of HLS_VARIANTS) {
      lines.push(
        `#EXT-X-STREAM-INF:BANDWIDTH=${v.bandwidth},RESOLUTION=${v.width}x${v.height},NAME="${v.name}"`,
      );
      lines.push(`${baseVideoUrl}?resolution=${v.name}`);
    }

    return lines.join('\n');
  }

  private async checkFfmpegAvailable(): Promise<boolean> {
    return new Promise((resolve) => {
      const proc = spawn('ffmpeg', ['-version']);
      proc.on('error', () => resolve(false));
      proc.on('close', (code) => resolve(code === 0));
    });
  }

  private async executeFfmpegHls(data: VideoHlsTranscodeJobData): Promise<{
    masterPlaylistUrl: string;
    thumbnailUrl?: string;
    blurhash?: string;
  }> {
    const tempDir = path.join(os.tmpdir(), `hls-${Date.now()}`);
    await fs.mkdir(tempDir, { recursive: true });

    const inputPath = path.join(tempDir, 'input.mp4');
    await fs.writeFile(inputPath, Buffer.from(data.sourceBufferBase64 || '', 'base64'));

    const thumbPath = path.join(tempDir, 'thumb.jpg');

    // Extract first frame for thumbnail and blurhash
    await new Promise<void>((resolve) => {
      const proc = spawn('ffmpeg', [
        '-i',
        inputPath,
        '-ss',
        '00:00:00.500',
        '-vframes',
        '1',
        thumbPath,
      ]);
      proc.on('close', () => resolve());
      proc.on('error', () => resolve());
    });

    let blurhash = 'L6PZfSi_.AyE_3t7t7R**0o#DgR4';
    try {
      const thumbBuf = await fs.readFile(thumbPath);
      const res = await generateBlurHash(thumbBuf);
      blurhash = res.blurhash;
    } catch {
      // ignore
    }

    // Clean up
    try {
      await fs.rm(tempDir, { recursive: true, force: true });
    } catch {
      // ignore
    }

    return {
      masterPlaylistUrl: `${data.videoUrl}#master.m3u8`,
      thumbnailUrl: `${data.videoUrl}#thumb.jpg`,
      blurhash,
    };
  }

  async onModuleDestroy(): Promise<void> {
    try {
      await this.worker?.close().catch(() => {});
      if (this.connection) {
        if (this.connection.status === 'ready' || this.connection.status === 'connect') {
          await this.connection.quit().catch(() => {});
        } else {
          this.connection.disconnect();
        }
      }
    } catch {
      // ignore on teardown
    }
  }
}
