apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base

labels:
  - pairs:
      Environment: Prod
    includeSelectors: false
    includeTemplates: true
