apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb
  labels:
    app.kubernetes.io/name: social-network-backend
    Service: social-network-backend
    Environment: Prod
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: social-network-backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  labels:
    app.kubernetes.io/name: social-network-frontend
    Service: social-network-frontend
    Environment: Prod
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: social-network-frontend
