apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

resources:
  - ../../base

labels:
  - pairs:
      Environment: Dev
    includeSelectors: false
    includeTemplates: true

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: social-network-backend
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: social-network-frontend
  - patch: |-
      - op: replace
        path: /spec/minAvailable
        value: 0
    target:
      kind: PodDisruptionBudget
      name: backend-pdb
  - patch: |-
      - op: replace
        path: /spec/minAvailable
        value: 0
    target:
      kind: PodDisruptionBudget
      name: frontend-pdb
