import {
  BellRing,
  Briefcase,
  Crown,
  Flame,
  Folder,
  Gamepad2,
  GraduationCap,
  Heart,
  Home,
  Lightbulb,
  MessageSquare,
  Music,
  Plane,
  Star,
  User,
  Users,
} from 'lucide-react';

export const folderIconOptions = [
  { key: 'messagesquare', icon: MessageSquare, label: 'All Chats' },
  { key: 'user', icon: User, label: 'Personal' },
  { key: 'users', icon: Users, label: 'Groups' },
  { key: 'bellring', icon: BellRing, label: 'Unread' },
  { key: 'flame', icon: Flame, label: 'Trending' },
  { key: 'folder', icon: Folder, label: 'Folder' },
  { key: 'heart', icon: Heart, label: 'Favorites' },
  { key: 'star', icon: Star, label: 'Starred' },
  { key: 'home', icon: Home, label: 'Home' },
  { key: 'briefcase', icon: Briefcase, label: 'Work' },
  { key: 'game', icon: Gamepad2, label: 'Games' },
  { key: 'music', icon: Music, label: 'Music' },
  { key: 'plane', icon: Plane, label: 'Travel' },
  { key: 'study', icon: GraduationCap, label: 'Study' },
  { key: 'idea', icon: Lightbulb, label: 'Ideas' },
  { key: 'crown', icon: Crown, label: 'VIP' },
];
