export const RESERVED_USERNAMES = [
  // Core System & Brand
  'eternal',
  'eternalnet',
  'theeternalnet',
  'eternalsocial',
  'theeternal',
  'admin',
  'administrator',
  'root',
  'mod',
  'moderator',
  'staff',
  'official',
  'system',
  'support',
  'security',
  'help',
  'helpdesk',
  'contact',
  'info',
  'team',
  'legal',
  'compliance',
  'billing',
  'press',
  'verified',
  'real',
  'test',
  'me',
  'you',
  'user',
  'account',
  'null',
  'undefined',

  // Core App Routes & Features
  'feed',
  'messages',
  'messenger',
  'chat',
  'explore',
  'search',
  'notifications',
  'settings',
  'profile',
  'reels',
  'music',
  'create',
  'saved',
  'bookmarks',
  'activity',
  'direct',
  'login',
  'signin',
  'signup',
  'register',
  'logout',
  'auth',
  'oauth',
  'forgot-password',
  'reset-password',
  'password',
  'download',
  'downloads',
  'apps',
  'install',
  'pwa',
  'desktop',
  'mobile',
  'web',

  // Company, Brand, Creators & Blog
  'about',
  'company',
  'company-information',
  'careers',
  'jobs',
  'brand',
  'branding',
  'news',
  'newsroom',
  'blog',
  'category',
  'creators',
  'guidelines',
  'rules',
  'community',

  // Safety & Trust Center
  'safety',
  'family',
  'family-center',
  'library',
  'safety-library',
  'privacy-hub',
  'transparency',
  'safety-news',
  'policies',
  'policy-hub',
  'teen-charter',
  'wellbeing',
  'law-enforcement',
  'law',
  'police',
  'faq',
  'help-center',
  'support-center',

  // Legal, Privacy & Terms
  'privacy',
  'privacy-policy',
  'terms',
  'terms-of-service',
  'tos',
  'cookie',
  'cookie-policy',
  'cookies',
  'regional-privacy',
  'gdpr',
  'ccpa',
  'retention',
  'retention-policy',
  'data-privacy-controls',
  'your-eternal-data-package',
  'your-data-package',
  'data',
  'export',
  'paid-services',
  'developer',
  'api',
  'developers',
  'applicant-candidate-privacy-policy',
  'applicant-privacy',
  'copyright',
  'dmca',
  'acknowledgements',
  'licenses',
  'license',
  'business',
  'marketing',
  'design',
  'engineering',

  // Technical & SEO Endpoints
  'sitemap',
  'sitemap.xml',
  'sitemap-static.xml',
  'robots.txt',
  'opensearch.xml',
  'security.txt',
  'well-known',
  'llms.txt',
  'llms-full.txt',
  'favicon.ico',
  'favicon.svg',
  'manifest.json',
  'graphql',
  'websocket',
  'ws',
  'socket',
  'cdn',
  'media',
  'static',
  'assets',
  'uploads',
  'avatars',
  'banners',
] as const;

export function isReservedUsername(username?: string | null): boolean {
  if (!username) return false;
  const clean = username.replace(/^@+/, '').trim().toLowerCase();
  return (RESERVED_USERNAMES as readonly string[]).includes(clean);
}

export const HARDENED_USERNAME_REGEX = /^(?![._])(?!.*[._]{2})[a-zA-Z0-9._]{2,32}(?<![._])$/;
