export const OUTBOX_REPOSITORY = Symbol('OUTBOX_REPOSITORY');

export const OUTBOX_STATUS = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  PUBLISHED: 'PUBLISHED',
  FAILED: 'FAILED',
} as const;

export const AGGREGATE_TYPES = {
  POST: 'POST',
  MESSAGE: 'MESSAGE',
  NOTIFICATION: 'NOTIFICATION',
  SHOWCASE: 'SHOWCASE',
  USER: 'USER',
} as const;

export const OUTBOX_EVENT_TYPES = {
  POST_CREATED: 'POST_CREATED',
  POST_UPDATED: 'POST_UPDATED',
  POST_DELETED: 'POST_DELETED',
  MESSAGE_SENT: 'MESSAGE_SENT',
  NOTIFICATION_CREATED: 'NOTIFICATION_CREATED',
  SEARCH_INDEX_POST: 'SEARCH_INDEX_POST',
} as const;

export const OUTBOX_PUBLISHER_LOCK_KEY = 'lock:outbox:publisher';
export const OUTBOX_MAX_RETRIES = 5;
export const OUTBOX_BATCH_SIZE = 50;
